### ISSUE TITLE
getFrameworkFromRegistry() throwing null reference exception on Mac

### ISSUE THREAD

**Issue by mickbyrne** [stripe/stripe-dotnet#990]
I'm trying to use the Stripe.net package in our server-side API. I started with a simple `customerService.create(...)` call, but got an exception with the following stack trace:

> Object reference not set to an instance of an object
> at Stripe.Infrastructure.Client.getFrameworkFromRegistry () [0x0001a] in <d01b79e1f9c84725be1db806a232e677>:0 \n  at Stripe.Infrastructure.Client.getSystemInformation () [0x00033] in <d01b79e1f9c84725be1db806a232e677>:0 \n  at Stripe.Infrastructure.Client.GetClientUserAgentString () [0x00077] in <d01b79e1f9c84725be1db806a232e677>:0 \n  at Stripe.Infrastructure.Client.ApplyClientData () [0x0000b] in <d01b79e1f9c84725be1db806a232e677>:0 \n  at Stripe.Infrastructure.Requestor.GetRequestMessage (System.String url, System.Net.Http.HttpMethod method, Stripe.StripeRequestOptions requestOptions, System.Boolean useBearer) [0x000af] in <d01b79e1f9c84725be1db806a232e677>:0 \n  at Stripe.Infrastructure.Requestor.PostString (System.String url, Stripe.StripeRequestOptions requestOptions) [0x00006] in <d01b79e1f9c84725be1db806a232e677>:0 \n  at Stripe.StripeCustomerService.Create (Stripe.StripeCustomerCreateOptions createOptions, Stripe.StripeRequestOptions requestOptions) [0x00014] in <d01b79e1f9c84725be1db806a232e677>:0 \n  at [ my code ]

I'm running Visual Studio for Mac using the .NET Framework 4.5.2 (Visual Studio for Mac is what has replaced Xamarin Studio). This uses the Mono 5.0.1.1 runtime.

The actual code that triggers this issue is super basic. Here's a gist of the relevant bits, https://gist.github.com/mickbyrne/df3835f34f5100a45e58d68002981213

This is a blocker for us at the moment. Do we need to roll our own HTTP handler for this (similar to issue https://github.com/stripe/stripe-dotnet/issues/567 re TLS?)

**Comment by mickbyrne** [comment]
I've verified that the code in the `Stripe.Infrastructure.Client.getFrameworkFromRegistry()` is throwing the error when running on a Mac. This is a simple method:

	private static string getFrameworkFromRegistry()
	{
		using (var key = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey("SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full\\"))
		{
			var releaseKey = Convert.ToInt32(key.GetValue("Release"));
			return get45Version(releaseKey);
		}
	}

On a Mac, the `key` is null. This works around the problem:

	private static string getFrameworkFromRegistry()
	{
		using (var key = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey("SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full\\"))
		{
			if(key != null)
			{
				var releaseKey = Convert.ToInt32(key.GetValue("Release"));
				return get45Version(releaseKey);
			}
			return "4.5 assumed, no registry key (maybe Mac or Linux)";
		}
	}

But then I'm not sure if this returned string (which gets added to the user agent string in requests to Stripe) is actually important or not.

**Comment by remi-stripe** [comment]
@mickbyrne We use the user-agent to identify users integration to help them debug. My guess is that you could potentially hardcode a new string instead when on Mac (or when that value is null) to send the version of the framework used another way so that this still gets reported reliably to Stripe.

**Comment by fred-stripe** [comment]
Hm, that's an interesting find! I do know that when you build & run with .NET core on a Mac the `#if NET45` code is elided by the CLR. I was not aware that Visual Studio for Mac shipped with a .NET 4.5 runtime. In my opinion this should work out of the box, so I'll download VS.NET, poke around, and see if we can find less fragile way to fetch this information. Thanks for the report & code!

**Comment by anelder-stripe** [comment]
@fred-stripe - It's worth noting that this block of code is also one of the two sources of problems in the permissions issue #971.  It requires full permissions to inspect the registry like it does, so it might be prudent to just fully replace it in favor of something a bit more naive.  It's sad, because we assumed this wouldn't make any impact when we added it last month, but it clearly did in a few unexpected ways.

@mickbyrne - Thanks so much for filing this!

**Comment by jaymedavis** [comment]
Could replace that method with

```
private static string getFrameworkFromRegistry()
{
    try
    {
        using (var key = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey("SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full\\"))
        {
            if(key != null)
            {
                var releaseKey = Convert.ToInt32(key.GetValue("Release"));
                return get45Version(releaseKey);
            }
            return "4.5 assumed, no registry key (maybe Mac or Linux)";
        }
    }
    catch (Exception)
    {
        return "registry lookup failed (mono?)";
    }
}
```

**Comment by jaymedavis** [comment]
I happened to stumble across [this](https://github.com/jhealy/aspdotnetcore/blob/master/SqlClientPlay20/SqlClientPlay20/Startup.cs#L84-L110) tonight... I can't remember if I tried using OSPlatform. If this actually works, it would be a better way of getting this information.

**Comment by nikkilocke** [comment]
This applies to Linux as well. You can't use registry keys on Mono - there is no registry!
My project, due for launch next week, is help up by this.

**Comment by ob-stripe** [comment]
Hey everyone, thanks for the feedback! We are planning on removing the registry access entirely -- as it turns out, even on Windows platforms there is no guarantee that the values read from the registry match that of the .NET runtime actually in use.

I don't have a firm ETA to provide but we're aiming to fix this ASAP. Thanks for your patience everyone!

**Comment by nikkilocke** [comment]
I have studied the mono sources, and found a workround for this problem.
Create the following folders (and make them accessable from whatever user is running your C# program)

`/etc/mono/registry/LocalMachine/software/microsoft/net framework setup/ndp/v4/full`

In the `full` folder at the bottom of this tree, create a file `values.xml` containing the following:

        <values>
        <value name="Release" type="string">393273</value>
        </values>

That is the mono equivalent of the registry key Stripe.net is looking for.

I have done this, and can go further, although I find errors later which I still have to investigate (e.g. transactions taking ages, and certificate exceptions).

**Comment by npalethorpe** [comment]
Has there been any progress to this? I appear to be running into this issue when using Visual Studio for Mac as described above. Is there an ETA on when it might be resolved?

**Comment by nikkilocke** [comment]
Have you tried the work round I posted above?
I have the latest Stripe, and it works fine for me (with the above workround).

**Comment by internetfx** [comment]
Why should a workaround be needed? Why assume Windows and ask for registry values for .NET these days?

**Comment by npalethorpe** [comment]
@nikkilocke I did try your workaround but I still receive the same exception. (The below call stack occurred after making a call to get a customer object).
```
Object reference not set to an instance of an object
  at Stripe.Infrastructure.Client.getFrameworkFromRegistry () [0x0001a] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Client.getSystemInformation () [0x00033] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Client.GetClientUserAgentString () [0x00077] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Client.ApplyClientData () [0x0000b] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Requestor.GetRequestMessage (System.String url, System.Net.Http.HttpMethod method, Stripe.StripeRequestOptions requestOptions) [0x000bf] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Requestor.GetString (System.String url, Stripe.StripeRequestOptions requestOptions) [0x00006] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.StripeCustomerService.Get (System.String customerId, Stripe.StripeRequestOptions requestOptions) [0x0001f] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
```

I did implement the ServiceStack.Stripe c# library and for the most part that works brilliantly, however I kept finding certain calls were not structured correctly or missing available attributes - it just seemed outdated.
 
Any help is appreciated!

**Comment by nikkilocke** [comment]
I agree it is ludicrous that this has not been fixed yet.

I only suggested my workround to help to get you going until they eventually did what they promised, and fixed the problem.

If you are still getting the exception, I can only assume you did not create the correct directory structure and file, or that your program does not have permission to access them.

If you want to get on with your project without waiting, I suggest you do what I did, and download the Stripe source, compile it, create a test module to call the relevant code, and debug through it to see what is going wrong.

**Comment by ob-stripe** [comment]
Hi everyone! I've just released version 15.3.1, which should finally fix this issue. The version should appear on NuGet in the next few minutes.

Really sorry it took us so long! I'm closing the issue, but feel free to reply if you're still having trouble.

**Comment by internetfx** [comment]
Hooray! Will definitely take a look.

**Comment by npalethorpe** [comment]
@ob-stripe  I hate to be the one to do this, but I've just updated to v15.3.1 and I'm still getting the same error...
```
Object reference not set to an instance of an object
  at Stripe.Infrastructure.Client.getFrameworkFromRegistry () [0x0001a] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Client.getSystemInformation () [0x00033] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Client.GetClientUserAgentString () [0x00077] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Client.ApplyClientData () [0x0000b] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Requestor.GetRequestMessage (System.String url, System.Net.Http.HttpMethod method, Stripe.StripeRequestOptions requestOptions) [0x000bf] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.Infrastructure.Requestor.GetString (System.String url, Stripe.StripeRequestOptions requestOptions) [0x00006] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
  at Stripe.StripeCustomerService.Get (System.String customerId, Stripe.StripeRequestOptions requestOptions) [0x0001f] in <fa0f4d2c6dc944308aee2ef8a4a71d04>:0 
```

It doesn't appear to matter what call I make to Stripe, each call I have tried results in the above error on the 'Get" function. Just for clarity the below is a basic example of something that will replicate the error for me:
```
StripeConfiguration.SetApiKey("MY_TEST_API_KEY");
var customerService = new StripeCustomerService();
Stripe.StripeCustomer customer = customerService.Get(userObj.StripeCustomerId, new StripeRequestOptions() { ApiKey = "MY_TEST_API_KEY" });
```

I am using Microsoft Visual Studio for Mac Community v7.5 Preview (7.5 build 933).
If someone else could confirm if the latest fix has resolved their issues I would appreciate it - it could very well be something I am doing, it just seems unlikely due to the error that is produced.

**Comment by turbo** [comment]
On mono latest and mono preview (.NET Framework, debian-based systems), this is now fixed.

**Comment by npalethorpe** [comment]
@jaymedavis you are correct! Visual Studio for Mac was holding on to a rogue dll, gave the bin folder a clean out and reinstalled the Stripe package and that appears to be working now! 👍 Thanks for the help :)
